#!/usr/bin/python
import json
import subprocess
#from pprint import pprint
import webbrowser

#initate duo script to output AWS status into JSON
subprocess.call(['./duo'])

# Display AWS services and status inside new browser window
webbrowser.open_new('http://ec2-54-67-74-97.us-west-1.compute.amazonaws.com/awscheck.html')
